import { Router } from "express";
import {
  createOrder,
  getOrderById,
  getMyOrders,
  getAllOrders,
  updateDeliveryFee,
  updateOrderStatus,
  cancelOrder,
  deleteOrder,
  handlePaystackWebhook,
} from "../controllers/orderControllers.js";
import { protect, authorize } from "../middleware/authMiddleware.js";

const router = Router();

/**
 * @openapi
 * tags:
 *   name: Orders
 *   description: E-commerce order lifecycle management, Paystack checkout, and delivery processing
 */

// ==========================================
// PUBLIC / WEBHOOK ROUTES
// ==========================================

/**
 * @openapi
 * /api/orders/webhook/paystack:
 *   post:
 *     summary: Paystack Webhook endpoint to auto-confirm payments
 *     description: Receives automated HTTP POST callbacks from Paystack to mark orders as paid. Validates HMAC SHA-512 signature from x-paystack-signature header.
 *     tags: [Orders]
 *     parameters:
 *       - in: header
 *         name: x-paystack-signature
 *         required: true
 *         schema:
 *           type: string
 *         description: HMAC SHA-512 signature generated by Paystack using your Secret Key.
 *         example: "a8f23b7c8e...90d1"
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - event
 *               - data
 *             properties:
 *               event:
 *                 type: string
 *                 example: "charge.success"
 *                 description: Paystack event trigger type
 *               data:
 *                 type: object
 *                 required:
 *                   - reference
 *                 properties:
 *                   reference:
 *                     type: string
 *                     example: "T1234567890"
 *                     description: Unique payment transaction reference stored during order creation
 *                   channel:
 *                     type: string
 *                     example: "card"
 *                     description: Payment method used (e.g., card, bank, ussd, bank_transfer)
 *                   gateway_response:
 *                     type: string
 *                     example: "Successful"
 *                     description: Gateway execution message
 *     responses:
 *       200:
 *         description: Webhook event processed or acknowledged successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 status:
 *                   type: string
 *                   example: "success"
 *       400:
 *         description: Invalid signature header or payload validation error
 *       500:
 *         description: Webhook processing error
 */
router.post("/webhook/paystack", handlePaystackWebhook);

// ==========================================
// AUTHENTICATED CUSTOMER ROUTES
// ==========================================

/**
 * @openapi
 * /api/orders:
 *   post:
 *     summary: Create a new order and initialize Paystack payment session
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - orderItems
 *               - shippingAddress
 *             properties:
 *               orderItems:
 *                 type: array
 *                 items:
 *                   type: object
 *                   required:
 *                     - product
 *                     - quantity
 *                   properties:
 *                     product:
 *                       type: string
 *                       example: "65a123456789abcdef123456"
 *                     quantity:
 *                       type: integer
 *                       example: 2
 *                     image:
 *                       type: string
 *                       example: "https://res.cloudinary.com/demo/image/upload/v1/product.jpg"
 *               shippingAddress:
 *                 type: object
 *                 required:
 *                   - fullName
 *                   - phoneNumber
 *                   - streetAddress
 *                   - city
 *                   - state
 *                 properties:
 *                   fullName:
 *                     type: string
 *                     example: "Egbeleke Taiwo"
 *                   phoneNumber:
 *                     type: string
 *                     example: "+2348012345678"
 *                   streetAddress:
 *                     type: string
 *                     example: "123 Commercial Avenue, Yaba"
 *                   city:
 *                     type: string
 *                     example: "Lagos"
 *                   state:
 *                     type: string
 *                     example: "Lagos"
 *                   country:
 *                     type: string
 *                     example: "Nigeria"
 *               paymentInfo:
 *                 type: object
 *                 properties:
 *                   paymentMethod:
 *                     type: string
 *                     enum: [paystack, card, bank_transfer]
 *                     example: "paystack"
 *     responses:
 *       201:
 *         description: Order created and Paystack payment session initialized successfully
 *       400:
 *         description: Missing required order items or shipping fields
 *       401:
 *         description: Not authorized
 *       404:
 *         description: Product not found
 *       500:
 *         description: Failed to create order
 */
router.post("/", protect, createOrder);

/**
 * @openapi
 * /api/orders/me:
 *   get:
 *     summary: Retrieve orders placed by the currently logged-in user
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     responses:
 *       200:
 *         description: User orders retrieved successfully
 *       401:
 *         description: Not authorized
 *       500:
 *         description: Error fetching user orders
 */
router.get("/me", protect, getMyOrders);

/**
 * @openapi
 * /api/orders/{id}:
 *   get:
 *     summary: Fetch a specific order by ID (Owner or Admin)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The MongoDB Order ID
 *         example: "65a123456789abcdef123456"
 *     responses:
 *       200:
 *         description: Order details retrieved successfully
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Not authorized to view this order
 *       404:
 *         description: Order not found
 *       500:
 *         description: Error fetching order
 */
router.get("/:id", protect, getOrderById);

/**
 * @openapi
 * /api/orders/{id}/cancel:
 *   put:
 *     summary: Self-service cancellation of an order (Owner only)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The MongoDB Order ID
 *         example: "65a123456789abcdef123456"
 *     requestBody:
 *       required: false
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               cancellationReason:
 *                 type: string
 *                 example: "Changed my mind before shipping"
 *     responses:
 *       200:
 *         description: Order cancelled successfully
 *       400:
 *         description: Order cannot be cancelled because it is already shipped/delivered
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Not authorized to cancel this order
 *       404:
 *         description: Order not found
 *       500:
 *         description: Failed to cancel order
 */
router.put("/:id/cancel", protect, cancelOrder);

// ==========================================
// ADMIN / STAFF MANAGEMENT ROUTES
// ==========================================

/**
 * @openapi
 * /api/orders:
 *   get:
 *     summary: Retrieve all orders across the system (Admin / Staff)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: query
 *         name: status
 *         schema:
 *           type: string
 *           enum: [pending, processing, shipped, delivered, cancelled]
 *         required: false
 *         description: Filter orders by current status
 *         example: "pending"
 *       - in: query
 *         name: isPaid
 *         schema:
 *           type: boolean
 *         required: false
 *         description: Filter orders by payment completion status
 *         example: true
 *       - in: query
 *         name: userId
 *         schema:
 *           type: string
 *         required: false
 *         description: Filter orders for a specific user MongoDB ID
 *         example: "65a123456789abcdef123456"
 *     responses:
 *       200:
 *         description: List of matched orders retrieved successfully
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Forbidden (Requires Admin or Staff role)
 *       500:
 *         description: Error retrieving orders
 */
router.get("/", protect, authorize("admin", "practitioner"), getAllOrders);

/**
 * @openapi
 * /api/orders/{id}/delivery-fee:
 *   put:
 *     summary: Update delivery fee for a specific order (Admin / Staff)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The MongoDB Order ID
 *         example: "65a123456789abcdef123456"
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - deliveryFee
 *             properties:
 *               deliveryFee:
 *                 type: number
 *                 example: 5000
 *     responses:
 *       200:
 *         description: Delivery fee updated successfully
 *       400:
 *         description: Valid non-negative delivery fee required
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Order not found
 *       500:
 *         description: Failed to update delivery fee
 */
router.put(
  "/:id/delivery-fee",
  protect,
  authorize("admin", "practitioner"),
  updateDeliveryFee
);

/**
 * @openapi
 * /api/orders/{id}/status:
 *   put:
 *     summary: Update order status lifecycle (Admin / Staff)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The MongoDB Order ID
 *         example: "65a123456789abcdef123456"
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - orderStatus
 *             properties:
 *               orderStatus:
 *                 type: string
 *                 enum: [pending, processing, shipped, delivered, cancelled]
 *                 example: "shipped"
 *     responses:
 *       200:
 *         description: Order status updated successfully
 *       400:
 *         description: Invalid order status
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Order not found
 *       500:
 *         description: Failed to update order status
 */
router.put(
  "/:id/status",
  protect,
  authorize("admin", "practitioner"),
  updateOrderStatus
);

/**
 * @openapi
 * /api/orders/{id}:
 *   delete:
 *     summary: Delete an order by ID (Admin / Staff)
 *     tags: [Orders]
 *     security:
 *       - BearerAuth: []
 *     parameters:
 *       - in: path
 *         name: id
 *         required: true
 *         schema:
 *           type: string
 *         description: The MongoDB Order ID
 *         example: "65a123456789abcdef123456"
 *     responses:
 *       200:
 *         description: Order deleted successfully
 *       400:
 *         description: Invalid order ID
 *       401:
 *         description: Not authorized
 *       403:
 *         description: Forbidden
 *       404:
 *         description: Order not found
 *       500:
 *         description: Failed to delete order
 */
router.delete(
  "/:id",
  protect,
  authorize("admin", "practitioner"),
  deleteOrder
);

export default router;